# Generated by Django 5.2.5 on 2025-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(verbose_name="Дата зачисления"),
        ),
    ]
